version: "3.7"

services:
  broker:
    build:
      context: broker
    ports:
      # opened for telnet testing
      - 4040:4040

  app:
    build:
      context: .
    command: sh -c "sleep 10 && elixir --sname broker@localhost -S mix run --no-halt"
    depends_on:
      - rtp-tweets-faf18x
      - broker
      - mongo

  rtp-tweets-faf18x:
    container_name: rtp-tweets-faf18x
    image: alexburlacu/rtp-server:faf18x
    ports:
      - 4000:4000

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
